# http://travis-ci.org/#!/ipython/ipywidgets
language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
env:
    - GROUP=python TRAVIS_NODE_VERSION=5.1
sudo: false
before_install:
    - 'if [[ $GROUP == python ]] ; then bash ./scripts/travis_before_install_py.sh ; fi'
install:
    - 'if [[ $GROUP == python ]] ; then bash ./scripts/travis_install_py.sh ; fi'
    - 'if [[ $GROUP == js ]] ; then bash ./jupyter-js-widgets/scripts/travis_install_js.sh ; fi'
script:
    - 'if [[ $GROUP == python ]] ; then bash ./scripts/travis_script_py.sh ; fi'
    - 'if [[ $GROUP == js ]] ; then bash ./jupyter-js-widgets/scripts/travis_script_js.sh ; fi'
matrix:
    include:
        - python: 3.5
          env: GROUP=js BROWSER=firefox TRAVIS_NODE_VERSION=5.1
after_success:
    - coveralls
