name: ipywidget_docs
channels:
- conda-forge
- defaults
dependencies:
- ipykernel
- jinja2
- jupyter_sphinx
- nbformat
- nbsphinx
- notebook>=4.2
- python=3.5
- sphinx=1.4.8
- sphinx>=1.4.6
- sphinx_rtd_theme
- tornado
- pip:
  - docutils<0.13.1
  - ipywidgets >=7.0.0a3
  - jupyter-alabaster-theme
  - python-dateutil
  - recommonmark==0.4.0
  